### ISSUE TITLE
Figure out a better way to present identified SAMPLES to the user

### ISSUE THREAD

**Issue by boulund** [ctmrbio/stag-mwc#129]
Currently, StaG prints a list of all identified samples so the user can troubleshoot if an incorrect number of samples are identified. This is printed in the main Snakefile, here: https://github.com/ctmrbio/stag-mwc/blob/develop/Snakefile#L55

There is an `onstart` handler, but as far as I can tell, it doesn't trigger on dryruns, which is a pity.

**Comment by AroArz** [comment]
Print statements also has the drawback of impeding creating DAG visualisations with dot e.g.

`snakemake --forceall --rulegraph | dot -Tpdf > dag.pdf`. A solution could be using.

```
from snakemake.logging import logger

logger.info("your print statement here!")
```

https://stackoverflow.com/questions/57530914/snakemake-forceall-dag-results-in-mysterius-error-stdin-syntax-error-in

**Comment by boulund** [comment]
True. I am not happy with how it is implemented now. Glad if you come up with a better solution :D

**Comment by boulund** [comment]
Moved the printout to the `onstart` handler.
