### ISSUE TITLE
BioBakery update (MetaPhlAn3, StrainPhlAn3, HUMAnN3)

### ISSUE THREAD

**Issue by AroArz** [ctmrbio/stag-mwc#158]
Seems there are some incompatibilities at the moment regarding MetaPhlAn, StrainPhlAn and HUMAnN. Now seems like a good time to issue an update together with the new releases of version 3 for all aforementioned tools. 

[branch 158-biobakery-update](https://github.com/ctmrbio/stag-mwc/tree/158-biobakery-update)

**Comment by boulund** [comment]
Does HUMAnN3 improve on the situation described in #75 ?

I'm guessing this will invalidate #138? 

Also, please make sure that it doesn't break the MPA2 heatmap plotting script (or include a suitable replacement) mentioned in #144. 

What about #49? Is that no longer relevant or does that issue need to be updated for MPA3?

**Comment by AroArz** [comment]
#49 I'm not really familiar with `-t rel_ab_w_read_stats` however according to https://forum.biobakery.org/t/metaphlan3-relative-abundance/564 and https://forum.biobakery.org/t/metaphlan-read-count-output-instead-of-relative-abundances/753 "It you want to use the estimated number of reads, you can re-run the analysis using -t rel_ab_w_read_stats".

#75 HUMAnN Still creates huge temp folders. I've had temp folder ranging from x5 - x20 in size? I don't know why the variation. There is an option to clean up the temp folders after the run `--remove-temp-output`. Once I get access to the Rackham again I'll experiment with using $SNIC_TMP, I feel like it should be possible to copy the output files to another directory. "This directory will be automatically created on your (first) compute node before the job starts and automatically deleted when the job has finished."

#138 I'm still testing but I feel like this should be resolved, will edit this post once I know for sure.

#144  The heat map still works for MPA3 output as such I have not edited it.

**Comment by AroArz** [comment]
Couldn't find an issue regarding this but I will also have to test whether this is still dysfunctional `/taxonomic_profiing/metaphlan2.smk`

```
        # This command is broken in MetaPhlAn2 v2.96.1 when running with old DB
        #metaphlan2krona.py \
        #    --profile {input.mpa_out} \
        #    --krona {output.krona} \
        #    2>&1 > {log}
```

**Comment by boulund** [comment]
Regarding #49, I think it would be nice to get some kind of estimated number of reads as a complement to the relative abundances you normally get out of MetaPhlAn. It's not very high priority, however.

I actually made a custom HUMAnN2 repo where I tried to patch HUMAnN2 to fix the temp dir issue (it was not configurable). Is it in version 3? That was the main issue. When running on UPPMAX, `$TMPDIR` is the same as `$SNIC_TMP`, so it's not that much of an issue. I agree with you that it is not good to make StaG too specific for UPPMAX. Perhaps it could be configured by the cluster profile if it really has to be?

Looking forward to the rest of your work!

**Comment by AroArz** [comment]
The tmp dir is not configurable however the output directory is, and the tmpdir will always be inside. I was thinking something like

```
rule humann2:
    """Functional profiling using HUMAnN2."""
    input:
        read1=OUTDIR/"host_removal/{sample}_1.fq.gz",
        read2=OUTDIR/"host_removal/{sample}_2.fq.gz",
        taxonomic_profile=OUTDIR/"metaphlan2/{sample}.metaphlan2.txt",
    output:
        OUTDIR/"humann2/{sample}_genefamilies.txt",
        OUTDIR/"humann2/{sample}_pathcoverage.txt",
        OUTDIR/"humann2/{sample}_pathabundance.txt",
    log:
        stdout=str(LOGDIR/"humann2/{sample}.humann2.stdout.log"),
        stderr=str(LOGDIR/"humann2/{sample}.humann2.stderr.log"),
    shadow:
        "shallow"
    conda:
        "../../envs/humann2.yaml"
    singularity:
        "shub://ctmrbio/stag-mwc:stag-mwc-biobakery"
    threads:
        cluster_config["humann2"]["n"] if "humann2" in cluster_config else 20
    resources:
        humann2=1
    params:
        outdir=OUTDIR/"humann2",
        tmpdir=$TMPDIR                                           ##Where $TMPDIR is /scratch/$SLURM_JOB_ID
        nucleotide_db=h_config["nucleotide_db"],
        protein_db=h_config["protein_db"],
    shell:
        """
        cat {input.read1} {input.read2} > concat_input_reads.fq.gz
        humann2 \
            --input concat_input_reads.fq.gz \
            --output {params.tmpdir} \
            --nucleotide-database {params.nucleotide_db} \
            --protein-database {params.protein_db} \
            --output-basename {wildcards.sample} \
            --threads {threads} \
            --taxonomic-profile {input.taxonomic_profile} \
            > {log.stdout} \
            2> {log.stderr}

        mv $TMPDIR/*.tsv {params.outdir}
        """
```

But I can't test just yet.

**Comment by boulund** [comment]
That looks like a good plan to. Let me know when you've tested it!

**Comment by AroArz** [comment]
This rule in `rules/functional_profiling/humann.smk` requires the `utility_mapping` mapping database. It enables selection of various different parameters in humann. You specify the path of the database in order to enable usage of those parameters, without it you're limited to few. You can specify the path like I've done however it is not possible to do so in docker or singularity, because of read-only file-systems. 

```bash
rule regroup_humann_tables:
    """regroup gene families"""
    input:
        genefamilies=f"{OUTDIR}/humann/{{sample}}_genefamilies_{HMN_METHOD}.tsv",
    output:
        genefamilies=f"{OUTDIR}/humann/{{sample}}_genefamilies_{HMN_METHOD}_{HMN_GRP}.tsv",
    log:
        stdout=f"{LOGDIR}/humann/{{sample}}.humann_sample_{HMN_METHOD}_{HMN_GRP}.stdout.log",
        stderr=f"{LOGDIR}/humann/{{sample}}.humann_sample_{HMN_METHOD}_{HMN_GRP}.stderr.log",
    shadow:
        "shallow"
    conda:
        "../../envs/humann.yaml"
    singularity:
        "shub://AroArz/singularity_playground:biobakery"
    threads: 
        1
    params:
        groups=h_config["groups"]
    shell:
        """
        humann_config \
            --update database_folders utility_mapping {HMN_UTILITY}
        humann_regroup_table \
            --input {input.genefamilies} \
            --output {output.genefamilies} \
            --groups {params.groups} \
            > {log.stdout} \
            2> {log.stderr}
        """
```

Options to adjust for this

1. Humann can only be run with `--use-conda`
2. We include a download of the database under that rule, and other rules which needs those parameters. We can remove it after the download, under the same rule, however this creates a necessity for internet, even with singularity when running the pipeline.
3. I create a image which downloads the utility database during build (db is roughly 2.5gb) and make some shell command tries to make the `humann.cfg` file point to the utility database, but doesn't fail the pipeline if that command fails. This way it will work with both `--use-conda`and `--use-singularity`.

**Comment by boulund** [comment]
Are you sure we cannot find a solution to mount the path of the DB into the singularity container file system so we can specify the path in the config anyway?

**Comment by AroArz** [comment]
It is possible to specify the path of all other databases with various options, except for the `utility_mapping`.  The `humann.cfg` file however specifies the path for the utility_mapping database and can be updated via 2 options.

1. `humann_config  --update database_folders utility_mapping {HMN_UTILITY}`
2. `humann_database --download utility_mapping full`

Option 1. does not work because it involves changing the `humann.cfg` file in a read-only file system. Option 2. works because the file is changed during the build of the image. The database is then stored inside of the image, ~ 3.6Gb total size.
[example](https://singularity-hub.org/containers/15056)

**Comment by boulund** [comment]
It might be possible to solve this by making sure the utility mapping database is available at the place defined in `humann.cfg` inside the image, even if we don't place the large utility mapping database there. We can cheat the system a bit by letting users bind a local utility mapping database into the image at runtime (e.g. with snakemake: `--singularity-args "-B /path/to/utility_mapping_db:/utility_mapping_db/`), if you understand what I mean?

**Comment by boulund** [comment]
This is now merged into develop
