### ISSUE TITLE
bracken2krona rule is broken

### ISSUE THREAD

**Issue by kcivkulis** [ctmrbio/stag-mwc#167]
Hello,

The rule `bracken2krona` fails with the following error:
```
...
Traceback (most recent call last):
  File "scripts/KrakenTools/kreport2krona.py", line 266, in <module>
    main()
  File "scripts/KrakenTools/kreport2krona.py", line 262, in main
    kreport2krona_main(args.r_file,args.o_file)
  File "scripts/KrakenTools/kreport2krona.py", line 165, in kreport2krona_main
    report_vals = process_kraken_report(line)
  File "scripts/KrakenTools/kreport2krona.py", line 79, in process_kraken_report
    lvl_reads = int(split_str[2])
ValueError: invalid literal for int() with base 10: 'S'
[Mon Apr 12 20:19:45 2021]
Error in rule bracken2krona:
    jobid: 0
    output: output_dir/kraken2/1.bracken.krona
    log: output_dir/logs/kraken2/1.bracken2krona.log (check log file(s) for error message)
    conda-env: /MYDIR/stag-mwc/.snakemake/conda/14a85743
    shell:

        scripts/KrakenTools/kreport2krona.py             --report-file output_dir/kraken2/1_bracken.kreport             --output output_dir/kraken2/1.bracken.krona             2>&1 > output_dir/logs/kraken2/1.bracken2krona.log

        (exited with non-zero exit code)

Exiting because a job execution failed. Look above for error message
...
```

The file `output_dir/kraken2/1_bracken.kreport` (which was generated by rule `bracken_kreport`) has the following format
`name    taxonomy_id     taxonomy_lvl    kraken_assigned_reads   added_reads     new_est_reads   fraction_total_reads` which obviously violates what is expected by script `kreport2krona.py`.

EDIT:
Judging by these:
https://github.com/jenniferlu717/Bracken/issues/84
https://github.com/jenniferlu717/Bracken/issues/124
it should work fine.

EDIT2:
Just a thought- maybe https://github.com/jenniferlu717/Bracken/blob/b014034d5c0efa7c4cb3eb9c1f0913c09cdce728/src/est_abundance.py#L487 is the file we actually have to pass to `kreport2krona.py`? It at least has the correct `.kreport` format.

**Comment by boulund** [comment]
Thanks for reporting about this issue.

It is something we've experienced several times as well, and most of the time it is caused by a broken input file. As you can see by the error message the `kreport2krona.py` is failing trying to convert the string `S` to an integer, which is most likely caused by a corrupt input file (a missing line break or something like that). Unfortunately, `kreport2krona.py` does not state which line in the input file that contains the error, but it can be modified to display it:

Modify lines [161-164](https://github.com/ctmrbio/stag-mwc/blob/master/scripts/KrakenTools/kreport2krona.py#L161-L164) in `scripts/KrakenTools/kreport2krona.py` like this. Change from:
```
    for line in r_file:
        line_num += 1
        #########################################
        report_vals = process_kraken_report(line)
```
to:
```
    for line in r_file:
        line_num += 1
        #########################################
        try:
            report_vals = process_kraken_report(line)
        except ValueError as e:
            raise ValueError("Could not process line {}: {}".format(line_num, e))
```

Have you tried deleting the input file and generating it again?

**Comment by boulund** [comment]
> Just a thought- maybe https://github.com/jenniferlu717/Bracken/blob/b014034d5c0efa7c4cb3eb9c1f0913c09cdce728/src/est_abundance.py#L487 is the file we actually have to pass to `kreport2krona.py`? It at least has the correct `.kreport` format.

Not sure what you mean here? The [`bracken_kreport`](https://github.com/ctmrbio/stag-mwc/blob/master/rules/taxonomic_profiling/kraken2.smk#L290-L319) rule is using `est_abundance.py` from Bracken to create the `output/kraken2/SAMPLE_bracken.kreport` file that is used as input for the [`bracken_mpa_style`](https://github.com/ctmrbio/stag-mwc/blob/master/rules/taxonomic_profiling/kraken2.smk#L353-L374) rule.

**Comment by kcivkulis** [comment]
> @kcivkulis
> Not sure what you mean here? The [`bracken_kreport`](https://github.com/ctmrbio/stag-mwc/blob/master/rules/taxonomic_profiling/kraken2.smk#L290-L319) rule is using `est_abundance.py` from Bracken to create the `output/kraken2/SAMPLE_bracken.kreport` file that is used as input for the [`bracken_mpa_style`](https://github.com/ctmrbio/stag-mwc/blob/master/rules/taxonomic_profiling/kraken2.smk#L353-L374) rule.


The created output file is also used as input for the `bracken2krona` rule. Are you really sure that the same file has to be passed both to `bracken_mpa_style` and `bracken2krona` rule? You can check the `kreport2krona.py` and see that it expects completely different file format. Maybe you should pass the generated kracken report file, not the output file?

**Comment by boulund** [comment]
Hmm... Yes, I see it now. Something is definitely wrong here. The output from the `bracken_kreport` rule should be in `.kreport` format, not the bracken format. I wonder how this could have happened, sorry! 

I'll get working on a fix asap.

**Comment by boulund** [comment]
@kcivkulis Please let me know if it works better for you now, if you try running StaG from the develop branch. I just made a small test and it seems to work as intended now. 
As soon as we merge the large biobakery update branch to develop we will prepare a new release of StaG, so the fix will make it to the master branch eventually.

**Comment by kcivkulis** [comment]
Just tested on our dataset- the rule passed successfully. Thank you.

**Comment by boulund** [comment]
Thank you very much for making me look into this issue in more detail so we could fix it!
