### ISSUE TITLE
Change container build service from singularity hub

### ISSUE THREAD

**Issue by boulund** [ctmrbio/stag-mwc#169]
https://singularityhub.github.io/singularityhub-docs/
> Singularity Hub is no longer online as a builder service, but exists as a read only archive. Containers built before April 19, 2021 are available at their same pull URLs. To see a last day gallery of Singularity Hub, please see here

We need to change to a new build service for our containers since Singularity Hub has stopped providing the service. Alternatives include changing to Docker images and auto-build them via e.g. [quay.io](https://quay.io/) or [Docker Hub](https://hub.docker.com/)

**Comment by AroArz** [comment]
We could consider hosting the containers here as well https://cloud.sylabs.io/home

**Comment by boulund** [comment]
I'm planning to do it like this:
1. Modify StaG to use as many biocontainer images as possible, and only use custom built images where absolutely necessary.
2. Use Github Actions to build the singularity images on pushes that modify conda env or singularity def files
3. Use repo secrets to store access keys to KI S3 system
4. Let the github actions workflow upload built images to a publicly accessible S3 bucket, e.g. `s3://ctmr-singularity/stag-mwc/main/image-version.sif`

**Comment by boulund** [comment]
Another alternative might be Github packages (ghcr):
https://github.com/singularityhub/github-ci

**Comment by boulund** [comment]
Done! We moved to building images with Github actions and distribution via ghcr.io
