### ISSUE TITLE
kreport2krona.py fails on candidate taxa

### ISSUE THREAD

**Issue by luhugerth** [ctmrbio/stag-mwc#171]
When the species name in a kraken kreport has more than two words, kreport2krona.py tries to parse the wrong column and crashes. 

An easy bypass is to make it easier to turn off krona plots in the config file.

**Comment by boulund** [comment]
This sounds like a bug that should be filed upstread, in KrakenTools (or maybe our local version in StaG is outdated).

https://github.com/jenniferlu717/KrakenTools

**Comment by boulund** [comment]
I'd like to follow up on this now that I'm updating KrakenTools for the next upcoming StaG release. I'll find some suitable samples that exhibit this problem and test on them with the latest version.

**Comment by boulund** [comment]
Since it is now possible to disable krona plots in the config file, I will consider this a non-issue until reopened in the future if there is still a need to have something fixed.
