### ISSUE TITLE
preprocessing_read_counts is confused about host DNA

### ISSUE THREAD

**Issue by luhugerth** [ctmrbio/stag-mwc#172]
It reports how many human reads are removed from each sample, rather than how many reads are left after host removal.

**Comment by boulund** [comment]
I guess the error is here:
https://github.com/ctmrbio/stag-mwc/blob/master/scripts/preprocessing_summary.py#L42-L48

It should report unclassified, not classified reads.

**Comment by boulund** [comment]
This is handled in the develop branch, but the fix hasn't yet made it into the master branch. I'll leave this issue here until it is merged.
