### ISSUE TITLE
make krona plots optional

### ISSUE THREAD

**Issue by luhugerth** [ctmrbio/stag-mwc#184]
No one uses the krona plots for the big projects (I think?) so even if it's a small thing, it's just taking up time in the queue and space in the server. It should be possible to disable it in the `config.yaml` file, perhaps for each classifier individually.

**Comment by boulund** [comment]
I like the idea. I'll have a look in the code base to see how if it be easily implemented.

**Comment by boulund** [comment]
https://github.com/ctmrbio/stag-mwc/pull/190
Done
