### ISSUE TITLE
Error in Bowtie2 and kraken2 db

### ISSUE THREAD

**Issue by mksherwani** [ctmrbio/stag-mwc#221]
WorkflowError in file /stagmwc/stag-mwc/workflow/rules/preproc/host_removal.smk, line 134:
Cannot find Bowtie2 database for host sequence removal at: './'!
Specify path to folder containing Bowtie2 database for host removal in config.yaml.
Note that the path should not contain the '.1.bt2' suffix.
  File "/stagmwc/stag-mwc/workflow/Snakefile", line 70, in <module>
  File "/stagmwc/stag-mwc/workflow/rules/preproc/host_removal.smk", line 134, in <module>

I tried resolving this error but I couldn't do it. 

Kindly help. I am new to this.

**Comment by boulund** [comment]
It appears you have not specified the path for the kraken2 or bowtie2 databases for host removal in the config file.

Please have a look in your local copy of the config file, [lines 65-77](https://github.com/ctmrbio/stag-mwc/blob/master/config/config.yaml#L65-L77), which contains the settings for the host removal step (it is located in `config/config.yaml` in your local copy of the repo). The StaG workflow does not come configured with any databases out-of-the-box: you need to download and prepare the relevant databases that you want to use. There are GRCh38-based reference databases for both Kraken2 and Bowtie2 available if you google for them, but note that you only need to use either Kraken2 or Bowtie2 for host removal, not both at the same time.
