### ISSUE TITLE
Improve automated reports from StaG-mwc

### ISSUE THREAD

**Issue by boulund** [ctmrbio/stag-mwc#41]
Snakemake has built-in functionality to produce [automated reports](http://snakemake.readthedocs.io/en/stable/tutorial/basics.html#tutorial-report). I would like to figure out if we could use this to produce something like module-level summaries containing the most important information into a nice overview report that can be used to assess the basic outcome of a StaG-mwc run.

**Comment by boulund** [comment]
I started a branch, `develop`, that has started to implement basic report functionality. I see now that to get plots directly in the HTML report they need to be in PNG or some other web-format. The PDFs only show up as downloadable links (which is also OK, I guess, but less quick to browse through). 
I also think that including any output that isn't summarizing across all samples is going to be very verbose, so I think we'll focus on putting summarizing plots in the report.

One more thing. It appears the report cannot be automatically created by Snakemake upon workflow completion, so the user has to run `snakemake --report report.html` to get the report after successfully completing a run.

**Comment by boulund** [comment]
The report is now created automatically. The reports are very uninformative, however. Some more work is needed to produce useful reports.

**Comment by lis4matilda** [comment]
Extend report to include statistics about read count per sample after different steps run in the pipeline. Should perhaps be in percentage of total number of reads after quality trim and mapping to hg19.

**Comment by boulund** [comment]
It annoys me to no end that `*.tsv` files are converted to HTML representations in the report. I think I'll rename all TSV output files to TXT to get rid of that.

**Comment by boulund** [comment]
I think this issue is resolved now. The statistics about read counts is currently only shown in proportions in the plot; the raw count data is available in the table.
