### ISSUE TITLE
conda: Placeholder of length '80' too short in package

### ISSUE THREAD

**Issue by boulund** [ctmrbio/stag-mwc#74]
There is a well-known issue with conda that occurs when installing older conda packages (built with `conda-build` < 2). The reason is that these packages come with binaries built with an assumption of path no longer than 80 characters. Conda packages built with a more recent version of `conda-build` increases this limit to 255, which should fix most issues. 

However, for StaG, the work around is to use `--conda-prefix` when running Snakemake to set an as short path as possible for the conda environments. In the worst case, maybe a symlink to a folder in in `/tmp` (e.g. `/tmp/symlink`, which points to `/my/long/path/somewhere/else`) might work? 

Edit: a link to what seems to be the most commonly cited issue about this: https://github.com/conda/conda/issues/4088

**Comment by lis4matilda** [comment]
Making a symlink to a folder did not work. Works well to use ``--conda-prefix`` and a folder with short path (eg. home directory)
