### ISSUE TITLE
Change BAM-file to be temporary file

### ISSUE THREAD

**Issue by lis4matilda** [ctmrbio/stag-mwc#78]
Remove BAM file when count-file is generated in mappers rule

**Comment by boulund** [comment]
Currently, only Bowtie2 creates a BAM file when mapping. I guess you want this to apply to the SAM file that is generated by BBMap as well? 

Actually, to simplify things we should consider converting the SAM output from BBMap to a BAM file as well, so we unify the output from mappers to be at least a BAM file. Not important right now, and easy to add later, but let's keep it in mind.

**Comment by boulund** [comment]
Actually, the more I think about it, deciding that all mappers rules should convert their output to a BAM file can simplify downstream handling, and essentially make it possible to reduce duplication of downstream rules by letting the BAM processing rules deal with all BAM files produced by mapping rules by including a wildcard for the mapper name in the output file path for BAM files.

**Comment by boulund** [comment]
Merged to develop, slated for next release.
