### ISSUE TITLE
bowtie mapping in StaG-mwc

### ISSUE THREAD

**Issue by kkraut** [ctmrbio/stag-mwc#92]
I'm new to StaG-mwc, but have a consistent error at the mapping step. Based on the slurm logs, I can see that there are two errors.

The first occurs after mapping to my first database, in what appears to be the summarizing mapping statistics step:

```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       14
        1

[Tue May 28 22:53:11 2019]
Job 0: Summarizing bowtie2 mapping statistics against ClusterSpecies.christenesella.bowtie2.

Changing to shadow directory: /domus/h1/kkraut/stag-mwc/.snakemake/shadow/tmpbwfwhnez
Activating conda environment: /home/kkraut/envs/31fe46a7
[Tue May 28 22:53:54 2019]
Error in rule 14:
    jobid: 0
    output: /proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/stag_output/bowtie2/ClusterSpecies.christenesella.bowtie2/1007522_S35.covstats.txt, /proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/stag_output/bowtie2/ClusterSpecies.christenesella.bowtie2/1007522_S35.rpkm.txt
    log: /proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/stag_output/logs/bowtie2/ClusterSpecies.christenesella.bowtie2/1007522_S35.pileup.log (check log file(s) for error message)
    conda-env: /home/kkraut/envs/31fe46a7
    shell:

            pileup.sh                 in=/proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/stag_output/bowtie2/ClusterSpecies.christenesella.bowtie2/1007522_S35.bam                 out=/proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/stag_output/bowtie2/ClusterSpecies.christenesella.bowtie2/1007522_S35.covstats.txt                 rpkm=/proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/stag_output/bowtie2/ClusterSpecies.christenesella.bowtie2/1007522_S35.rpkm.txt                 2> /proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/stag_output/logs/bowtie2/ClusterSpecies.christenesella.bowtie2/1007522_S35.pileup.log


Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
slurmstepd: error: Detected 2 oom-kill event(s) in step 8973997.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
```

The second error occurs when mapping to my second database, and appears to result in a called process error:
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       17
        1

[Tue May 28 22:53:12 2019]
Job 0: Mapping 1007522_S35 to GlobalGeneCat_bowtie2 using Bowtie2

Activating conda environment: /home/kkraut/envs/359b0580
Traceback (most recent call last):
  File "/domus/h1/kkraut/stag-mwc/.snakemake/scripts/tmpfhn6carc.wrapper.py", line 25, in <module>
    "(bowtie2 --threads {snakemake.threads} {snakemake.params.extra} "
  File "/home/kkraut/miniconda3/lib/python3.6/site-packages/snakemake/shell.py", line 149, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  (bowtie2 --threads 8  -x /proj/uppstore2017
096/b2014011/db/medusa/GlobalGeneCat_bowtie2 -1 /proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/
fastq_test/stag_output/filtered_human/1007522_S35_R1.filtered_human.fq.gz -2 /proj/uppstore2017096/b201
4011_nobackup/kimmy/FinnTwin/fastq_test/stag_output/filtered_human/1007522_S35_R2.filtered_human.fq.gz
| samtools view -Sbh -o /proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/stag_output/b
owtie2/GlobalGeneCat_bowtie2/1007522_S35.bam -)  > /proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/stag_output/logs/bowtie2/GlobalGeneCat_bowtie2/1007522_S35.log 2>&1' returned non-zero exit status 1.
[Tue May 28 22:53:17 2019]
Error in rule 17:
    jobid: 0
    output: /proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/stag_output/bowtie2/GlobalGeneCat_bowtie2/1007522_S35.bam
    log: /proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/stag_output/logs/bowtie2/GlobalGeneCat_bowtie2/1007522_S35.log (check log file(s) for error message)
    conda-env: /home/kkraut/envs/359b0580

RuleException:
CalledProcessError in line 75 of /domus/h1/kkraut/stag-mwc/rules/mappers/bowtie2.smk:
Command 'source /home/kkraut/miniconda3/bin/activate '/home/kkraut/envs/359b0580'; set -euo pipefail;  python /domus/h1/kkraut/stag-mwc/.snakemake/scripts/tmpfhn6carc.wrapper.py' returned non-zero exit status 1.
  File "/domus/h1/kkraut/stag-mwc/rules/mappers/bowtie2.smk", line 75, in __rule_14
  File "/home/kkraut/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job 17 since they might be corrupted:
/proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/stag_output/bowtie2/GlobalGeneCat_bowtie2/1007522_S35.bam
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```
When I check the output, I do have a .bam file after mapping to my first database, but an empty directory for the second one. As far as I can tell/find, there is no additional output after this step. 

Here is my original command call. I am currently running it from my base environment (where I installed snakemake) because I cannot call snakemake from my stag-mwc environment. I'm not sure if this is part of the problem? I can find snakemake in my binaries within the stag-mwc directory (where I call the command from), but as soon as I activate the stag-mwc env, I can no longer call snakemake.
```
(base)
kkraut /home/kkraut/stag-mwc → snakemake --use-conda --profile cluster_configs/rackham/ --configfile kim_config.yaml --prefix /home/kkraut/envs/ --keep-going
```

I'm not sure how to troubleshoot further, and welcome any help!

**Comment by boulund** [comment]
Thanks for reporting your issue! 

First, let's find all the relevant log files and have a look at them. The log directory is specified in your config file, start by having a look there (and please upload them to this issue if they contain anything of importance). 

We also need to figure out exactly which version of StaG you're running, it's easiest to go to the source folder and open `Snakefile` and check line 17 in that file.  They main thing I want to know is really if you're on the `master` branch or the `develop` branch.

**Comment by kkraut** [comment]
Noted! I looked at the rackham.yaml file and, if I'm reading it correctly, the default setting has everything running as a "core" job, which has a limit of 6.4GB of RAM per core, and we are requesting 8 cores on that node for a total of 51.2GB of RAM for the bowtie step. Is this correct? 

Default settings at the beginning of rackham.yaml:
```
 Cluster config file for StaG-mwc for use on UPPMAX Rackham
__default__:
    account: "snic2018-3-350"
    partition: "core"
    extra: ""
    time: "03:00:00"
    n: 2
    stderr: "slurm_logs/slurm-{rule}-{wildcards}.stderr"
    stdout: "slurm_logs/slurm-{rule}-{wildcards}.stdout"
    jobname: "[{rule}]: {wildcards}" 
```
farther down in the rackham.yaml file:
```
#############################
# Mappers
#############################
bbmap:
    n: 8
    time: "02:00:00"
bowtie2:
    n: 8
    time: "02:00:00"
```

So, to allocate more memory to the bowtie portion of the job, I think I have two options: (1) to request more cores (based on the SLURM docs I can request up to 10 on rackham for a core job, so I can add 2 more to the current 8?), or (2) I can run it as a "node" job instead, which then gets to use the entire 128GB of RAM on the node. Do you have a recommendation? Have I understood this correctly? 

Thanks!

**Comment by boulund** [comment]
Yes, it sounds like you have got a handle on this already.

The default settings are used for all jobs, unless there are overrides further down in the file. However, I just realized/remembered that I re-implemented the mapping steps as anonymous Snakemake jobs, so they all adhere to the default allocations and cannot be overridden. The bowtie2-section in `rackham.yaml` doesn't do anything anymore and should actually be removed. 

I think you should just increase the default allocations in `rackham.yaml` to something much higher. It has the downside of increasing the probability that you have to wait longer in the queue for the slurm jobs to run.

Resource allocation on Slurm for the mapping-related parts of StaG is an unsolved issue. It is an unfortunate side effect of the implementation of anonymous rules in Snakemake and I'm very happy to listen to suggestion for improvement!

**Comment by kkraut** [comment]
Okay - here's an update:
I first tried running it still as a core job, but maximizing the memory assigned to it (max is 64 GB on rackham) still threw an out of memory error. Thus, I ended up running it as a node job and requested only a single node:
```
# Cluster config file for StaG-mwc for use on UPPMAX Rackham
__default__:
    account: "snic2018-3-350"
    partition: "node"
    extra: ""
    time: "03:00:00"
    n: 1
    stderr: "slurm_logs/slurm-{rule}-{wildcards}.stderr"
    stdout: "slurm_logs/slurm-{rule}-{wildcards}.stdout"
    jobname: "[{rule}]: {wildcards}"
```
I got the workflow to run to completion if I only ran bowtie with our first database, but if I try to run it with two databases, I continue to get a CalledProcessError. Here's the SLURM log:

```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 20
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       13
        1

[Sun Jun  2 17:27:56 2019]
Job 0: Mapping 1007522_S35 to GlobalGeneCat_bowtie2 using Bowtie2

Activating conda environment: /home/kkraut/envs/359b0580
Traceback (most recent call last):
  File "/domus/h1/kkraut/stag-mwc/.snakemake/scripts/tmp1hfgv25a.wrapper.py", line 25, in <module>
    "(bowtie2 --threads {snakemake.threads} {snakemake.params.extra} "
  File "/home/kkraut/miniconda3/lib/python3.6/site-packages/snakemake/shell.py", line 149, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  (bowtie2 --threads 8  -x /proj/uppstore2017096/b2014011/db/medusa/GlobalGeneCat_bowtie2 -1 /proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/onlyglobalgenecat_output/filtered_human/1007522_S35_R1.filtered_human.fq.gz -2 /proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/onlyglobalgenecat_output/filtered_human/1007522_S35_R2.filtered_human.fq.gz | samtools view -Sbh -o /proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/onlyglobalgenecat_output/bowtie2/GlobalGeneCat_bowtie2/1007522_S35.bam -)  > /proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/stag_output/logs/bowtie2/GlobalGeneCat_bowtie2/1007522_S35.log 2>&1' returned non-zero exit status 1.
[Sun Jun  2 17:28:00 2019]
Error in rule 13:
    jobid: 0
    output: /proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/onlyglobalgenecat_output/bowtie2/GlobalGeneCat_bowtie2/1007522_S35.bam
    log: /proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/stag_output/logs/bowtie2/GlobalGeneCat_bowtie2/1007522_S35.log (check log file(s) for error message)
    conda-env: /home/kkraut/envs/359b0580

RuleException:
CalledProcessError in line 75 of /domus/h1/kkraut/stag-mwc/rules/mappers/bowtie2.smk:
Command 'source /home/kkraut/miniconda3/bin/activate '/home/kkraut/envs/359b0580'; set -euo pipefail;  python /domus/h1/kkraut/stag-mwc/.snakemake/scripts/tmp1hfgv25a.wrapper.py' returned non-zero exit status 1.
  File "/domus/h1/kkraut/stag-mwc/rules/mappers/bowtie2.smk", line 75, in __rule_14
  File "/home/kkraut/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job 13 since they might be corrupted:
/proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/onlyglobalgenecat_output/bowtie2/GlobalGeneCat_bowtie2/1007522_S35.bam
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

```

I am running: stag version 0.3.3-dev. 

Also worth noting is that even though the workflow completed without errors for the first database, for some reason none of the annotations are working. Thus all counts files are entirely 0s. Here's a brief snippet of the counts.log file:

```
WARNING: Found no annotation for 'gi|331001527|ref|NZ_GL883679.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|331001541|ref|NZ_GL883693.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|313116175|ref|NZ_GL538289.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|325478283|gb|AEXM01000033.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|34495455|ref|NC_005085.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|343924883|ref|NZ_BACI01000029.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|320469229|gb|GL638238.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|223045154|ref|NZ_ACEP01000104.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|341591997|gb|AFUI01000003.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|329958219|ref|NZ_GL882580.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|365968300|ref|NC_016514.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|223667696|ref|NZ_DS264516.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|374290092|ref|NC_016621.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|224485799|ref|NZ_EQ973651.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|330998616|ref|NZ_GL883851.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|336437946|ref|NZ_GL945179.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|329959038|ref|NZ_GL882589.1|', assigning to 'Unknown'
WARNING: Found no annotation for 'gi|303229730|ref|NZ_AEDS01000053.1|', assigning to 'Unknown'
```

I gratefully welcome any input!

**Comment by boulund** [comment]
> I first tried running it still as a core job, but maximizing the memory assigned to it (max is 64 GB on rackham) still threw an out of memory error. 
Did you only modify the requested memory  or also the amount of cores? The reason I'm asking is that on Rackham the amount of requested memory is not taken into account, because memory allocation is only determined by the number of requested cores.

>I got the workflow to run to completion if I only ran bowtie with our first database, but if I try to run it with two databases, I continue to get a CalledProcessError. Here's the SLURM log:
Ok, this is a bit more tricky. I'd like to see the log files from the mapping job, if they exist.

>Also worth noting is that even though the workflow completed without errors for the first database, for some reason none of the annotations are working. Thus all counts files are entirely 0s. Here's a brief snippet of the counts.log file:
It would be helpful if you could share the SAM/BAM file from the mapping and a part of your reference database with me (or at least the full headers of some of the sequences) to troubleshoot. I seem to recall @lis4matilda encountered a similar issue previously, do you remember @lis4matilda?

**Comment by kkraut** [comment]
> Did you only modify the requested memory or also the amount of cores? The reason I'm asking is that on Rackham the amount of requested memory is not taken into account, because memory allocation is only determined by the number of requested cores.

In my initial attempt to increase the amount of RAM dedicated to the job, I requested the maximum of 10 cores (this gave 64GB of RAM) on rackham node and ran it as a core job. This still generated an out-of-memory error. So then I switched the job type to a node job, which uses the entire node and gets all 128GB of RAM. This did the trick! So the job requires somewhere between >64 and <= 128 GB RAM.

> Ok, this is a bit more tricky. I'd like to see the log files from the mapping job, if they exist.

Github doesn't support the file extentions on the log files, so I cannot attach them here, but will email them to you. The .stdout files are all empty. The error log you will be most interested in is the one for job #13 (the complete text of which is also above in my previous post).

>It would be helpful if you could share the SAM/BAM file from the mapping and a part of your reference database with me (or at least the full headers of some of the sequences) to troubleshoot. 

The BAM is too large to attach here, so I will email you a link to it.

>I seem to recall @lis4matilda encountered a similar issue previously, do you remember @lis4matilda?

Yes, this was a known issue when discussing with @lis4matilda, but as far as I know it has not been resolved yet?

**Comment by boulund** [comment]
I tried following the log files you provided to try to see where the issue occurs, and it seems the mapping of GlobalGeneCat worked well, and also the pileup. However, it seems it failed on creating the count table from the pileup output:

```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 20
Rules claiming more threads will be scaled down.
Job counts:
    count   jobs
    1   19
    1

[Mon Jun  3 15:24:50 2019]
Job 0: Creating count table for mappings to GlobalGeneCat_bowtie2_index

Changing to shadow directory: /domus/h1/kkraut/stag-mwc/.snakemake/shadow/tmpckqjgsnj
Activating conda environment: /home/kkraut/envs/31fe46a7
Waiting at most 5 seconds for missing files.
MissingOutputException in line 107 of /domus/h1/kkraut/stag-mwc/rules/mappers/bowtie2.smk:
Missing files after 5 seconds:
/proj/uppstore2017096/b2014011_nobackup/kimmy/FinnTwin/fastq_test/stag_output/bowtie2/GlobalGeneCat_bowtie2_index/counts.KO.tsv
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```
If your reference gene catalog is large the pileup file will be huge, which could take some time to synchronize from the node to the shared file system. You could try to run the workflow with `--latency-wait 60` or something like that (I think the default waiting time is like 5 seconds).

**Comment by boulund** [comment]
>In my initial attempt to increase the amount of RAM dedicated to the job, I requested the maximum of 10 cores (this gave 64GB of RAM) on rackham node and ran it as a core job. This still generated an out-of-memory error. So then I switched the job type to a node job, which uses the entire node and gets all 128GB of RAM. This did the trick! So the job requires somewhere between >64 and <= 128 GB RAM.

Uff, that is a lot of memory for a single sample. But if it works I guess that's fine, it just means you'll have to wait a lot in queue and burn through core hours rather quickly. Can you check the run statistics from the node jobs after they completed to see how much memory and cores were actually used? UPPMAX has some resources to help you find that (https://www.uppmax.uu.se/support/user-guides/jobstats-user-guide/).

**Comment by boulund** [comment]
Closing this for now. Let me know if you are still having issues @kkraut.
